spring:
  datasource:
    url: jdbc:h2:file:./test
    username: sa # default
    password: # default
    driver-class-name: org.h2.Driver # default
  h2.console.enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug